github: sabeechen
patreon: stephenbeechen
custom:
  - https://www.buymeacoffee.com/sabeechen
  - https://www.paypal.com/paypalme/stephenbeechen
  - https://github.com/sabeechen/hassio-google-drive-backup/blob/master/donate-crypto.md
