name: push_to_prod
on: 
  workflow_dispatch:

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
  
    - name: Check out dev repo
      uses: actions/checkout@v4
      with:
        path: dev
        persist-credentials: false

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Addon Image
      uses: home-assistant/builder@master
      with:
        args: |
          --all \
          --target dev/hassio-google-drive-backup \
          --docker-hub ghcr.io
